# Generated by Django 3.2.6 on 2023-06-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('expiry', models.DateField()),
                ('userid', models.IntegerField()),
                ('api_key', models.TextField()),
                ('package', models.IntegerField()),
                ('tokens', models.IntegerField()),
            ],
        ),
    ]
